<?php
// <!-- phpDesigner :: Timestamp [1/26/2011 3:50:22 PM] -->
/**
 * @file
 * Qualifies users so they don't need to be shown a captcha
 * 
 * Only users with javascript enabled and a session cookie 
 * can submit the form. Bots should have neither.
 */
function avoid_captcha_form_alter(&$form, &$form_state, $form_id)
{
    global $base_url;
    // $base_url seems to be available even if not in settings.php
    // so the following 3 lines are not needed.
    //if (!isset($base_url) || strstr($base_url, 'www') == FALSE) {
    //$base_url = variable_get('avoid_captcha_base_url', 'base URL');
    //}
    // Add needed javascript that runs when the page loads

    $in_settings = variable_get('avoid_captcha_form_ids', array());
    if (in_array($form_id, $in_settings)) {
        $selector_id = str_replace('_', '-', $form_id);
        $js_add = 'jQuery(document).ready( function(){jQuery(".warning").remove();
jQuery.get("' . $base_url .
            '/sites/all/modules/custom/avoidcaptcha/cap_sub/token.php",function(txt){
jQuery("#' . $selector_id . '").append(\'<input type="hidden" name="ts" value="\'+txt+\'" />\');
});
});';
        $javascript = drupal_add_js($js_add, 'inline');

        // Add warning when javascript is not detected
        $form['nojavascript'] = array('#prefix' =>
            '<p class="warning"><span style="color:red;">', '#markup' => t('You must have javascript enabled to use this form.'),
            '#suffix' => '</span></p>', '#weight' => -5, );

        // Give it a function for validation
        $form['#validate'][] = 'avoid_captcha_form_validate';

    }
}

// trying to add code that validates on submit prior to proccessing.
function avoid_captcha_form_validate($form, &$form_state)
{

    $proceed = false;
    $seconds = 60 * 10; //10 minutes

    if (isset($_POST['ts']) && isset($_COOKIE['token']) && $_COOKIE['token'] == md5
        ('africa byby' . $_POST['ts'])) {
        $proceed = true;
    }

    if (!$proceed) {
        form_set_error('', t('Form processing halted for suspicious activity'));
    } else
        if (((int)$_POST['ts'] + $seconds) < mktime()) {
            form_set_error('', t('Too much time elapsed'));
        }
}

// For admin below
/**
 * Implement hook_menu().
 */
function avoid_captcha_menu()
{

    $items['admin/config/system/avoid-captcha'] = array('title' => 'Avoid Captcha',
        'description' => 'Manage which forms should be protected with Avoid Captcha.',
        'page callback' => 'drupal_get_form', 'page arguments' => array('avoid_captcha_settings'),
        'access arguments' => array('administer avoid captcha'), 'type' =>
        MENU_NORMAL_ITEM, 'file' => 'avoid_captcha.admin.inc', );
    return $items;
}
/**
 * For admin submit function
 */
function avoid_captcha_admin_submit($form, &$form_state)
{
    variable_set('avoid_captcha_form_ids', array_filter($form_state['values']['protect_forms']));

}
/**
 * Implement hook_permission
 */
function avoid_captcha_permission()
{
    return array('administer avoid captcha' => array('title' => t('Administer Avoid Captcha'),
        'description' => t('Perform administration tasks for Avoid Captcha.')), );
}
